#!/usr/bin/env bash
mkdir -p dist
echo "build src/ldview.ls -> dist/ldview.js ..."
./node_modules/.bin/lsc -cbp src/ldview.ls > dist/ldview.js
echo "minifying ldview.js ..."
./node_modules/.bin/uglifyjs dist/ldview.js > dist/ldview.min.js
echo "done."

